version: 1

sources:

  - name: generic
    database: drivfit-data-warehouse
    tables:
      - name: calendar

  - name: odoo
    database: drivfit-data-warehouse
    tables:
      - name: account_account
      - name: account_analytic_account
      - name: account_analytic_line
      - name: account_partial_reconcile
      - name: account_move_line
      - name: account_move
      - name: account_journal
      - name: account_payment
      - name: fleet_vehicle
      - name: fleet_vehicle_deal
      - name: fleet_vehicle_damage_log
      - name: fleet_vehicle_insurance
      - name: fleet_vehicle_insurance_claim
      - name: fleet_vehicle_inspection
      - name: fleet_vehicle_log_contract
      - name: fleet_vehicle_cost
      - name: fleet_vehicle_model
      - name: fleet_vehicle_model_brand
      - name: fleet_vehicle_odometer
      - name: fleet_vehicle_station
      - name: hr_employee
      - name: hr_department
      - name: ir_translation
      - name: product_product
      - name: product_template
      - name: product_category
      - name: rate_base
      - name: rental_contract
      - name: res_country_city
      - name: res_country
      - name: res_partner
      - name: sale_order
      - name: sale_order_line
      - name: support_stage
      - name: support_ticket
      - name: support_ticket_category
      - name: support_ticket_theme
      - name: vehicle_category

  - name: quatenus
    database: drivfit-data-warehouse
    tables:
      - name: extendedEvents
      - name: journal